PRINT N'Задолженность по кредиту №1 (выплаты пустые):';
PRINT dbo.ScaleLoanAmount(GETDATE(), 1);

PRINT N'Задолженность по кредиту №3 (выплаты пустые):';
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -17, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -16, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -15, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -14, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -13, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -12, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -11, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -10, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -9, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -8, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -7, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -6, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -5, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -4, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -3, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -2, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -1, GETDATE()), 3);
PRINT dbo.ScaleLoanAmount(GETDATE(), 3);

PRINT N'Задолженность по кредиту №11 (выплаты пустые):';
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -17, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -16, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -15, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -14, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -13, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -12, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -11, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -10, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -9, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -8, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -7, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -6, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -5, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -4, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -3, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -2, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(DATEADD(MONTH, -1, GETDATE()), 11);
PRINT dbo.ScaleLoanAmount(GETDATE(), 11);